# Site settings
title: wuxudong
email: xudong82113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes about tech
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wuxudong.github.io" # the base hostname & protocol for your site
github_username:  wuxudong

# Build settings
markdown: redcarpet

paginate: 10

author: wuxudong

gems: [jekyll-paginate]
