# Site settings
title: wuxudong
email: xudong82113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 吴旭东的博客 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wuxudong.github.io" # the base hostname & protocol for your site
github_username:  wuxudong

# Build settings
#markdown: kramdown

paginate: 10

author: wuxudong

gems: [jekyll-paginate]
